#!/bin/bash

usage() {
    echo "Usage: dynamic-dns-bootstrap [OPTION]"
    echo "Bootstrap Dynamic DNS Utility"
    echo ""
    echo "  --base"
    echo "    Base directory where the dynamic dns client will be installed."
    echo ""
    echo "  --dev"
    echo "    Install and check development dependencies."
    echo ""
    exit
}

DEV=no
while [ "$1" != "" ]; do
    case $1 in
        --dev )                         DEV=yes
                                        ;;
        --base )                        shift
                                        BASE=$1
                                        ;;
        -h | --help )                   usage
                                        ;;
        * )                             usage
                                        ;;
    esac
    shift
done

[ -z $BASE ] && usage

type node   >/dev/null 2>&1 || { echo >&2 "I require 'node' but it's not installed. Aborting."; exit 1; }
type npm    >/dev/null 2>&1 || { echo >&2 "I require 'npm' but it's not installed. Aborting."; exit 1; }
type git    >/dev/null 2>&1 || { echo >&2 "I require 'git' but it's not installed. Aborting."; exit 1; }

if [ "$DEV" == "yes" ]; then
    type python3   >/dev/null 2>&1 || { echo >&2 "I require 'python3' but it's not installed. Aborting."; exit 1; }
fi

echo ""
echo ""
echo "= Install serverless framework"
echo "==============================================================================="
if [ type serverless >/dev/null 2>&1 ]; then
    npm install -g serverless
else
    echo "--> Serverless already installed"
fi
echo ""

echo ""
echo "= Clone Dynamic DNS Utility from github.com"
echo "==============================================================================="
git clone https://github.com/amarkwalder/dynamicdns.git $BASE
cd $BASE
echo ""

echo ""
echo "= Install node dependencies"
echo "==============================================================================="
npm install
echo "--> Node dependencies installed"
echo ""

if [ "$DEV" == "yes" ]; then

    echo ""
    echo "= DEV: Install virtual python3 environment"
    echo "==============================================================================="
    python3 -m venv .dyndns-venv
    source .dyndns-venv/bin/activate
    echo "--> Virtual python3 environment installed"
    echo ""

    echo ""
    echo "= DEV: Install pip-tools"
    echo "==============================================================================="
    pip install pip-tools
    echo "--> pip-tools installed"
    echo ""

    echo ""
    echo "= DEV: Install python dependencies via pip-sync"
    echo "==============================================================================="
    pip-sync requirements.txt requirements-dev.txt
    echo "--> Python dependencies installed"
    echo ""

fi

echo ""
echo ""
echo "= IMPORTANT"
echo "= Manual Steps"
echo "==============================================================================="
echo ""
echo "--> AWS Credentials"
echo "--> Setup Route 53 DNS domain"
echo "--> Setup certificate in AWS Certificate Manager"
echo "--> Validate certificate in AWS Certificate Manager"
echo "--> Setup S3 private bucket for configuration files"
echo ""
echo ""
