#!/bin/bash

usage() {
    echo "Usage: dynamic-dns-deploy [OPTION]"
    echo "Install local runtime environment for deploying Dynamic DNS Utility to AWS"
    echo ""
    echo "  -s, --stage <stage>         Stage to deploy to AWS."
    echo ""
    echo "Important"
    echo "AWS Client and Serverless framework require AWS access key id and secret."
    echo "Make sure the access key id and secret is ready and exported as environment variables or"
    echo "located in the AWS credential file (~/.aws/credentials)."
    echo ""
    echo "export AWS_ACCESS_KEY_ID=[secure]"
    echo "export AWS_SECRET_ACCESS_KEY=[secure]"
    echo ""
    exit
}

while [ "$1" != "" ]; do
    case $1 in
        -s | --stage )                  shift
                                        STAGE=$1
                                        ;;
        -h | --help )                   usage
                                        ;;
        * )                             usage
                                        ;;
    esac
    shift
done

BASEDIR=$(dirname "$0")/../..

[ -z $STAGE ] && usage
[ ! -f $HOME/.aws/credentials ] && ( [ -z $AWS_ACCESS_KEY_ID ] || [ -z $AWS_SECRET_ACCESS_KEY ] ) && usage
type serverless   >/dev/null 2>&1 || { echo >&2 "I require 'serverless' but it's not installed. Aborting."; exit 1; }
[ -f $BASEDIR/config/serverless-$STAGE.config.yml ] || { echo >&2 "Looking for 'config/serverless-$STAGE.config.yml', but not found. Aborting."; exit 1; } 

cd $BASEDIR

echo ""
echo ""
echo "= Deploy Dynamic DNS Utility"
echo "==============================================================================="
serverless deploy --stage=$STAGE
echo "--> Dynamic DNS Utility deployed"

echo ""
echo ""
echo "= Create domain for Dynamic DNS Utility"
echo "==============================================================================="
serverless create_domain --stage=$STAGE
echo "--> Dynamic DNS Utility domain created"
echo ""
echo ""
