#!/bin/bash

usage() {
    echo "Usage: dynamic-dns-config [OPTION]"
    echo "Create configuration files for Dynamic DNS Utility"
    echo ""
    echo "  --silent"
    echo "    Silent installation, parameters are passed via command line or environment variables."
    echo ""
    echo "  --stage <stage>"
    echo "    Stage name used in configuration files and afterwards on AWS."
    echo ""
    echo "  --hostname <hostname>"
    echo "    Hostname used to update / create on AWS (Route 53)."
    echo ""
    echo "  --shared-secret <shared secret>"
    echo "    Shared secret used to hash the parameters and check during communication."
    echo ""
    echo "  --api-domain-name <API domain name>"
    echo "    Domain name including host to use for Cloudfront e.g. api.domain.com."
    echo ""
    echo "  --api-domain-certificate-name <API domain certificate name>"
    echo "    SSL certificate name used for https on AWS."
    echo "    IMPORTANT: Generated certificate name has to match the API domain name, otherwise the certificate won't be accepted."
    echo ""
    echo "  --route53-region <Route 53 - region>"
    echo "    Route 53 region where your DNS domain is located."
    echo ""
    echo "  --route53-zone-id <Route 53 - zone id>"
    echo "    Route 53 zone id which will be updated and where your hostname to update will be located."
    echo ""
    echo "  --route53-record-ttl <Route 53 - record ttl>"
    echo "    Route 53 record time to live (ttl) to be used."
    echo ""
    echo "  --route53-record-type <Route 53 - record type>"
    echo "    Route 53 record type to be used (most of the time this will be A)."
    echo ""
    echo "  --s3-region <S3 - Region>"
    echo "    S3 region where your S3 configuration bucket is located."
    echo ""
    echo "  --s3-bucket <S3 - Bucket>"
    echo "    S3 bucket where your configuration file is found."
    echo ""
    echo "  --s3-key <S3 - Key>" 
    echo "    S3 key where your configuration file is found."
    echo ""   
    exit
}

replace-tokens() {
    FILE=$1
    replace "@@URL@@" "$URL" $FILE
    replace "@@DNS_HOSTNAME@@" "$DNS_HOSTNAME" $FILE
    replace "@@SHARED_SECRET@@" "$SHARED_SECRET" $FILE
    replace "@@API_DOMAIN_NAME@@" "$API_DOMAIN_NAME" $FILE
    replace "@@API_DOMAIN_CERTIFICATE_NAME@@" "$API_DOMAIN_CERTIFICATE_NAME" $FILE
    replace "@@ROUTE53_REGION@@" "$ROUTE53_REGION" $FILE
    replace "@@ROUTE53_ZONE_ID@@" "$ROUTE53_ZONE_ID" $FILE
    replace "@@ROUTE53_RECORD_TTL@@" "$ROUTE53_RECORD_TTL" $FILE
    replace "@@ROUTE53_RECORD_TYPE@@" "$ROUTE53_RECORD_TYPE" $FILE
    replace "@@S3_REGION@@" "$S3_REGION" $FILE
    replace "@@S3_BUCKET@@" "$S3_BUCKET" $FILE
    replace "@@S3_KEY@@" "$S3_KEY" $FILE
} 

function replace {
  sed -i "s/$(echo $1 | sed -e 's/\([[\/.*]\|\]\)/\\&/g')/$(echo $2 | sed -e 's/[\/&]/\\&/g')/g" $3
}

type read   >/dev/null 2>&1 || { echo >&2 "I require 'read' but it's not installed. Aborting."; exit 1; }
type sed    >/dev/null 2>&1 || { echo >&2 "I require 'sed' but it's not installed. Aborting."; exit 1; }

SILENT=no
while [ "$1" != "" ]; do
    case $1 in
        --silent )                      shift
                                        SILENT=yes
                                        ;;
        --stage )                       shift
                                        STAGE=$1
                                        ;;
        --hostname )                    shift
                                        DNS_HOSTNAME=$1
                                        ;;
        --shared-secret )               shift
                                        SHARED_SECRET=$1
                                        ;;
        --api-domain-name )             shift
                                        API_DOMAIN_NAME=$1
                                        ;;
        --api-domain-certificate-name ) shift
                                        API_DOMAIN_CERTIFICATE_NAME=$1
                                        ;;
        --route53-region )              shift
                                        ROUTE53_REGION=$1
                                        ;;
        --route53-zone-id )             shift
                                        ROUTE53_ZONE_ID=$1
                                        ;;
        --route53-record-ttl )          shift
                                        ROUTE53_RECORD_TTL=$1
                                        ;;
        --route53-record-type )         shift
                                        ROUTE53_RECORD_TYPE=$1
                                        ;;
        --s3-region )                   shift
                                        S3_REGION=$1
                                        ;;
        --s3-bucket )                   shift
                                        S3_BUCKET=$1
                                        ;;
        --s3-key )                      shift
                                        S3_KEY=$1
                                        ;;
        -h | --help )                   usage
                                        ;;
        * )                             usage
                                        ;;
    esac
    shift
done

if [ "$SILENT" == "no" ]; then
    echo ""
    echo ""
    echo "= Enter Configuration Values"
    echo "==============================================================================="
    echo ""
    read -p "Stage                          : " STAGE
    read -p "Hostname                       : " DNS_HOSTNAME
    read -p "Shared Secret                  : " SHARED_SECRET
    read -p "API Domain - Name              : " API_DOMAIN_NAME
    read -p "API Domain - Certificate Name  : " API_DOMAIN_CERTIFICATE_NAME
    read -p "Route53 - Region               : " ROUTE53_REGION
    read -p "Route53 - Zone ID              : " ROUTE53_ZONE_ID
    read -p "Route53 - Record TTL           : " ROUTE53_RECORD_TTL
    read -p "Route53 - Record Type          : " ROUTE53_RECORD_TYPE
    read -p "S3 - Region                    : " S3_REGION
    read -p "S3 - Bucket                    : " S3_BUCKET
    echo ""
fi


[ -z $STAGE ] && usage
[ -z $DNS_HOSTNAME ] && usage
[ -z $SHARED_SECRET ] && usage
[ -z $API_DOMAIN_NAME ] && usage
[ -z $API_DOMAIN_CERTIFICATE_NAME ] && usage
[ -z $ROUTE53_REGION ] && usage
[ -z $ROUTE53_ZONE_ID ] && usage
[ -z $ROUTE53_RECORD_TTL ] && usage
[ -z $ROUTE53_RECORD_TYPE ] && usage
[ -z $S3_REGION ] && usage
[ -z $S3_BUCKET ] && usage

S3_KEY=server-$STAGE.config

URL=https://$API_DOMAIN_NAME

BASEDIR=$(dirname "$0")
CONFIGDIR=$BASEDIR/../../config/

cp $CONFIGDIR/server.config.template $CONFIGDIR/server-$STAGE.config
replace-tokens $CONFIGDIR/server-$STAGE.config

cp $CONFIGDIR/serverless.config.yml.template $CONFIGDIR/serverless-$STAGE.config.yml
replace-tokens $CONFIGDIR/serverless-$STAGE.config.yml

cp $CONFIGDIR/client.config.template $CONFIGDIR/client-$STAGE.config
replace-tokens $CONFIGDIR/client-$STAGE.config

echo ""
echo ""
echo "= Successfully created config files"
echo "==============================================================================="
echo ""
echo "--> $CONFIGDIR/server-$STAGE.config"
echo "--> $CONFIGDIR/serverless-$STAGE.config.yml"
echo "--> $CONFIGDIR/client-$STAGE.config"
echo ""
echo ""
echo ""
echo ""
echo "= IMPORTANT"
echo "= Manual Steps"
echo "==============================================================================="
echo ""
echo "--> Upload file '$CONFIGDIR/$S3_KEY' to S3 bucket '$S3_BUCKET' in '$S3_REGION'"
echo ""
echo ""

exit 0